In [1]:
import duckdb

In [2]:
con = duckdb.connect("research.duckdb")

In [3]:
con.execute("SHOW TABLES").df()

                       name
0      current_eps_features
1           current_eps_raw
2       master_developments
3     master_historical_eps
4  master_historical_prices

0. current_eps_features: table of current stock eps data with z-scores
1. current_eps_raw: the raw eps data from excel, no z-scores
2. master_developments: This has every relevant news headline and description for our universe going back to 2014
3. master_historical_eps: This has the loaded historical eps data
4. master_historical_prices: This has the laoded historical price data

Deleted Tables
1. dates_w_universe: ~7,500 companies in our historical universe. Also the dates which we will extract data for
2. historical_eps_formula: for each company in 'dates_w_universe', there is a corresponding row for every date. For every row there is a CIQ exel formula, which if opened in excel and reloaded, will download the needed data. Earnings per share estimates
3. historical_price_formula: for each company in 'dates_w_universe', there is a corresponding row for every date. For every row there is a CIQ exel formula, which if opened in excel and reloaded, will download the needed data. Price and volume data

In [9]:
con.execute("SELECT * FROM current_eps_features LIMIT 10").df()

,entity_name_raw,iqid,exchange,sp_sector,mktcap_usd_m,n_est_fy1,eps_fy1_current,eps_fy1_1m_ago,eps_fy1_3m_ago,eps_median_est,eps_high_est,eps_low_est,eps_surprise,asof_date,rev_1m,rev_3m,rev_1m_z_score,rev_3m_z_score
0,"Charter Communications, Inc. (NASDAQGS:CHTR)",4121481,NASDAQGS,Communication Services,29408.91,12.0,43.55,43.40,36.03,42.30,52.43,37.39,1.09,06/03/2026,0.003456,0.208715,-0.187050,-0.124376
1,Tencent Music Entertainment Group (NYSE:TME),9962087,NYSE,Communication Services,21096.08,22.0,0.86,0.86,0.86,0.86,0.91,0.78,3.59,06/03/2026,0.000000,0.000000,-0.188497,-0.135352
2,"Clear Channel Outdoor Holdings, Inc. (NYSE:CCO)",4121662,NYSE,Communication Services,1181.42,4.0,-0.09,0.04,0.04,-0.10,-0.05,-0.12,0.00,06/03/2026,-3.250000,-3.250000,-1.549232,-0.306262
3,Comcast Corporation (NASDAQGS:CMCSA),4057180,NASDAQGS,Communication Services,114807.27,17.0,3.68,3.68,4.22,3.66,3.94,3.51,2.62,06/03/2026,0.000000,-0.127962,-0.188497,-0.142081
4,"DoubleVerify Holdings, Inc. (NYSE:DV)",28172255,NYSE,Communication Services,1783.49,8.0,1.12,0.96,0.96,1.15,1.30,0.93,-8.33,06/03/2026,0.166667,0.166667,-0.118716,-0.126587
5,EchoStar Corporation (NASDAQGS:SATS),4190757,NASDAQGS,Communication Services,30690.17,2.0,0.41,-40.41,-39.24,0.41,2.66,-1.85,-24.75,06/03/2026,1.010146,1.010449,0.234438,-0.082215
6,Electronic Arts Inc. (NASDAQGS:EA),4100183,NASDAQGS,Communication Services,49550.24,21.0,8.59,8.63,8.61,8.55,9.83,7.72,7.76,06/03/2026,-0.004635,-0.002323,-0.190438,-0.135474
7,Formula One Group (NASDAQGS:FWON.K),4996388,NASDAQGS,Communication Services,20824.53,7.0,1.65,2.21,2.23,1.63,1.91,1.41,-2.25,06/03/2026,-0.253394,-0.260090,-0.294590,-0.149030
8,Fox Corporation (NASDAQGS:FOXA),13518181,NASDAQGS,Communication Services,24201.06,17.0,4.63,4.62,4.47,4.66,4.86,4.32,6.22,06/03/2026,0.002165,0.035794,-0.187591,-0.133470
9,Grindr Inc. (NYSE:GRND),5264620,NYSE,Communication Services,2149.56,5.0,0.55,0.49,0.49,0.54,0.60,0.49,-10.42,06/03/2026,0.122449,0.122449,-0.137230,-0.128913

In [8]:
con.execute("SELECT * FROM master_historical_eps LIMIT 10").df()

,AS_OF,company_name,IQID,exchange,sector,marketcap,num_est,eps_est,surprise
0,2014-09-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,330.049988,4,0.23,9.09
1,2014-10-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,488.570007,1,0.26,-4.35
2,2014-11-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,513.510010,4,0.47,-4.35
3,2014-12-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,514.669983,4,0.46,-4.35
4,2015-01-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,528.789978,4,0.46,-4.35
5,2015-02-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,506.329987,4,0.46,-4.35
6,2015-03-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,807.539978,4,0.47,-4.35
7,2015-04-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,760.960022,5,0.47,-4.35
8,2015-05-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,660.010010,4,0.52,-4.35
9,2015-06-01,"1-800-FLOWERS.COM, Inc. (NASDAQGS:FLWS)",4122591,NASDAQGS,Consumer Discretionary,629.130005,4,0.51,-4.35

In [83]:

# This is how you would add the 3 months ago eps estimate to a table.
# Running the code multiple times seems to result in a different output for some reason.
con.execute("""
            WITH features AS (
            SELECT 
                p1.AS_OF,
                p1.company_name,
                p1.sector,
                p1.eps_est as eps_est,
                p2.eps_est as eps_est_1m,
                p3.eps_est as eps_est_3m
            FROM master_historical_eps p1
            LEFT JOIN master_historical_eps p2
                ON p1.IQID = p2.IQID
                AND DATE_TRUNC('month', p2.AS_OF) = DATE_TRUNC('month', p1.AS_OF - INTERVAL 1 MONTH)
            LEFT JOIN master_historical_eps p3
                ON p1.IQID = p3.IQID
                AND DATE_TRUNC('month', p3.AS_OF) = DATE_TRUNC('month', p1.AS_OF - INTERVAL 3 MONTH)
            ORDER BY p1.company_name, p1.IQID, p1.AS_OF
            --LIMIT 10 OFFSET 90000
            )

            -- first with statement end */
            SELECT
                *,
                CASE 
                    WHEN eps_est_1m IS NULL OR ABS(eps_est_1m) < 1e-6 THEN NULL
                    ELSE (eps_est - eps_est_1m) / ABS(eps_est_1m)
                END AS rev_1m,
                CASE 
                    WHEN eps_est_3m IS NULL OR ABS(eps_est_3m) < 1e-6 THEN NULL
                    ELSE (eps_est - eps_est_3m) / ABS(eps_est_3m)
                END AS rev_3m,
                (rev_1m - AVG(rev_1m) OVER (PARTITION BY AS_OF, sector)) /
                    (STDDEV_POP(rev_1m) OVER (PARTITION BY AS_OF, sector)) AS z_1m,
                (rev_3m - AVG(rev_3m) OVER (PARTITION BY AS_OF, sector)) /
                    (STDDEV_POP(rev_3m) OVER (PARTITION BY AS_OF, sector)) AS z_3m
            
            FROM features
            WHERE eps_est_3m IS NOT NULL

""").df()

,AS_OF,company_name,sector,eps_est,eps_est_1m,eps_est_3m,rev_1m,rev_3m,z_1m,z_3m
0,2025-08-01,"Copa Holdings, S.A. (NYSE:CPA)",Industrials,16.09,16.049999,15.68,0.002492,0.026148,0.078052,0.075761
1,2025-08-01,"Copart, Inc. (NASDAQGS:CPRT)",Industrials,1.55,1.550000,1.58,0.000000,-0.018987,0.069571,0.051614
2,2025-08-01,Bloom Energy Corporation (NYSE:BE),Industrials,0.50,0.460000,0.44,0.086957,0.136364,0.365472,0.134726
3,2025-08-01,Blue Bird Corporation (NASDAQGM:BLBD),Industrials,3.83,3.830000,3.99,0.000000,-0.040100,0.069571,0.040318
4,2025-08-01,"Core & Main, Inc. (NYSE:CNM)",Industrials,2.51,2.510000,2.45,0.000000,0.024490,0.069571,0.074874
...,...,...,...,...,...,...,...,...,...,...
322005,2024-08-01,"Confluent, Inc. (NASDAQGS:CFLT)",Information Technology,0.21,0.200000,0.17,0.050000,0.235294,-0.019148,0.084240
322006,2024-08-01,"Autodesk, Inc. (NASDAQGS:ADSK)",Information Technology,8.14,8.140000,8.06,0.000000,0.009926,-0.079021,-0.037991
322007,2024-08-01,"Gartner, Inc. (NYSE:IT)",Information Technology,11.60,11.590000,11.59,0.000863,0.000863,-0.077988,-0.042907
322008,2024-08-01,"AvePoint, Inc. (NASDAQGS:AVPT)",Information Technology,0.17,0.170000,0.11,0.000000,0.545455,-0.079021,0.252459
322009,2024-08-01,Gen Digital Inc. (NASDAQGS:GEN),Information Technology,2.20,2.200000,1.95,0.000000,0.128205,-0.079021,0.026159

In [49]:
con.execute("""
SELECT
    AS_OF,
    sector,
    COUNT(*) as n
FROM master_historical_eps
GROUP BY AS_OF, sector
ORDER BY n ASC
LIMIT 20;


""").df()

        AS_OF sector   n
0  2015-04-01   None  95
1  2019-02-01   None  95
2  2016-06-01   None  95
3  2020-05-01   None  95
4  2019-12-01   None  95
5  2016-10-01   None  95
6  2018-06-01   None  95
7  2021-05-01   None  95
8  2021-04-01   None  95
9  2019-07-01   None  95
10 2025-02-01   None  95
11 2016-11-01   None  95
12 2017-08-01   None  95
13 2016-03-01   None  95
14 2025-12-01   None  95
15 2023-01-01   None  95
16 2023-11-01   None  95
17 2020-06-01   None  95
18 2024-10-01   None  95
19 2015-06-01   None  95

### Which companies have no price data

In [5]:
con.execute("SELECT IQID FROM master_historical_prices GROUP BY IQID HAVING MAX(adj_close) IS NULL OR MAX(volume) IS NULL").df()

         IQID
0     4977373
1     4986059
2     4038045
3      101229
4     4977372
...       ...
3471  4965651
3472  4968473
3473   100748
3474  4964075
3475  4998226

[3476 rows x 1 columns]