In [1]:
import duckdb

In [ ]:
con = duckdb.connect("research.duckdb")

In [9]:
con.execute("SHOW TABLES").df()

                       name
0      current_eps_features
1           current_eps_raw
2          dates_w_universe
3    historical_eps_formula
4  historical_price_formula
5       master_developments
6     master_historical_eps
7  master_historical_prices

0. current_eps_features: table of current stock eps data with z-scores
1. current_eps_raw: the raw eps data from excel, no z-scores
2. dates_w_universe: ~7,500 companies in our historical universe. Also the dates which we will extract data for
4. historical_eps_formula: for each company in 'dates_w_universe', there is a corresponding row for every date. For every row there is a CIQ exel formula, which if opened in excel and reloaded, will download the needed data. Earnings per share estimates
5. historical_price_formula: for each company in 'dates_w_universe', there is a corresponding row for every date. For every row there is a CIQ exel formula, which if opened in excel and reloaded, will download the needed data. Price and volume data
6. master_developments: This has every relevant news headline and description for our universe going back to 2014
7. master_historical_eps: This has the loaded historical eps data
8. master_historical_prices: This has the laoded historical price data

In [ ]:

# This is how you would add the 3 months ago eps estimate to a table.
# Running the code multiple times seems to result in a different output for some reason.
con.execute("""
            SELECT 
                p1.AS_OF,
                p1.company_name,
                p1.eps_est as eps_est,
                p2.eps_est as eps_est_3m
            FROM master_historical_eps p1
            LEFT JOIN master_historical_eps p2
                ON p1.IQID = p2.IQID
                AND p2.AS_OF = p1.AS_OF - INTERVAL 3 MONTH
            LIMIT 10

""").df()

       AS_OF                           company_name  eps_est  eps_est_3m
0 2021-01-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.29        2.27
1 2021-02-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.34        2.27
2 2021-03-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.40        2.28
3 2021-04-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.40        2.29
4 2021-05-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.40        2.34
5 2021-06-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.36        2.40
6 2021-07-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.37        2.40
7 2021-08-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.37        2.40
8 2021-09-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.50        2.36
9 2021-10-01  Mercury Systems, Inc. (NASDAQGS:MRCY)     2.50        2.37